---
title: "Autoencoders for Demonsion Reduction"
author: "Zhejia Dong & Tabib Chowdhury"
date: "2023-05-04"
header-includes:
  - \usepackage{color}
  - \usepackage{geometry}
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{xcolor}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage[font=large]{caption}
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
    math: katex
---

```{r setup, include=FALSE,echo=TRUE}
knitr::opts_chunk$set(message = F)
knitr::opts_chunk$set(warning = F)
knitr::opts_chunk$set(echo = FALSE, eval = TRUE,cache=TRUE,warning = FALSE,message = FALSE)
knitr::opts_chunk$set(fig.height = 3)
knitr::opts_chunk$set(fig.width = 4.5)
knitr::opts_chunk$set(fig.align="center")
```

```{r library, include=FALSE,echo=TRUE}
library(tidyverse)
library(tidyr)
library(lubridate)
library(kableExtra)
library(knitr)
library(reshape2)
library(data.table)
library(ggplot2)
library(ggthemes)
library(tensorflow)
library(keras)
library(tfdatasets)
library(ggfortify)
```


## Introduction

## What is Autoencoder?

## Variations of autoencoder models

## Autoencoder versus PCA

## Applications of Autoencoders

## Implementation Antoencoder for Dimension Reduction


```{r}

```

## Conclusion

[^1]



[^1]: <http://zhejiadong.github.io/PHP2650FinalProject>.



## Reference

